apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-client-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: codesandtags/client:latest
          env:
            - name: PORT
              value: "3000"
            - name: EVENTS_API
              value: http://event-bus-service:4005
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
