apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-event-bus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: codesandtags/event-bus:latest
          env:
            - name: PORT
              value: "4005"
            - name: POSTS_API
              value: http://posts-service:4000
            - name: COMMENTS_API
              value: http://comments-service:4001
            - name: QUERY_API
              value: http://query-service:4002
            - name: MODERATION_API
              value: http://moderation-service:4003
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
