apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-moderation-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: codesandtags/moderation:latest
          env:
            - name: PORT
              value: "4003"
            - name: EVENTS_API
              value: http://event-bus-service:4005
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
