apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-posts-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: codesandtags/posts:latest
          env:
            - name: PORT
              value: "4000"
            - name: EVENTS_API
              value: http://event-bus-service:4005
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
