apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-query-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: codesandtags/query:latest
          env:
            - name: PORT
              value: "4002"
            - name: EVENTS_API
              value: http://event-bus-service:4005
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
